version = 2

disabled_plugins = [
    "io.containerd.tracing.processor.v1.otlp",
    "io.containerd.internal.v1.tracing",
]

imports = [
    "/etc/cri/conf.d/cri.toml",
]

[debug]
level = "info"
format = "json"
