# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.5.2"

pre_release = false

preface = """\
"""

[notes]

    [notes.updates]
        title = "Component Updates"
        description="""\
Kubernetes: v1.28.2
Linux: 6.1.54
"""

    [notes.cgroupsv1]
        title = "cgroups v1"
        description="""\
Talos Linux is incompatible with cgroups v1 due to the Kubernetes issue
https://github.com/kubernetes/kubernetes/issues/120813 and new version of Linux kernel.

Talos Linux doesn't use cgroups v1 by default, and it has to be explicitly enabled with
a kernel argument: `talos.unified_cgroup_hierarchy=0`, so if you are not using cgroups v1,
you are not affected.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
