# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.3.0"

pre_release = true

preface = """\
"""

[notes]

    [notes.updates]
        title = "Component Updates"
        description="""\
* Linux: 6.1.1
* containerd: v1.6.14

Talos is built with Go 1.19.4.
"""

    [notes.etcd]
        title = "etcd Maintenance"
        description="""\
Talos adds new APIs to make it easier to perform etcd maintenance operations.

These APIs are available via new `talosctl etcd` sub-commands:

* `talosctl etcd alarm list|disarm`
* `talosctl etcd defrag`
* `talosctl etcd status`

See also [etcd maintenance guide](https://talos.dev/v1.4/advanced/etcd-maintenance/).
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
