# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.0.4"

pre_release = false

preface = """\
"""

[notes]
    [notes.updates]
        title = "Component Updates"
        description="""\
* Linux: 5.15.45
* Containerd: v1.6.6
* Runc: 1.1.2
* CoreDNS: v1.9.2

Talos is built with Go 1.17.11
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
