# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.5.0"

pre_release = true

preface = """\
"""

[notes]
    [notes.firmware]
        title = "Linux Firmware"
        description = """\
Starting with Talos 1.6, there is no Linux firmware included in the initramfs.
Customers who need Linux firmware can pull them as extension during install time using the image service.
If the initial boot requires firmware, a custom iso can be built with the firmware included using the imager service.
This also ensures that the linux-firmware is not tied to a specific Talos version.
"""

    [notes.updates]
        title = "Component Updates"
        description = """\
Linux: 6.1.51
CoreDNS: v1.11.1
Kubernetes: v1.28.1

Talos is built with Go 1.21.1.
"""

    [notes.talosctl]
        title = "talosctl CLI"
        description = """\
The command `images` deprecated in Talos 1.5 was removed, please use `talosctl images default` instead.
"""

    [notes.device-selectors]
        title = "Network Device Selectors"
        description = """\
Previously, [network device selectors](https://www.talos.dev/v1.6/talos-guides/network/device-selector/) only matched the first link, now the configuration is applied to all matching links.
"""



[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
