# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.7.0"

pre_release = true

preface = """\
"""

[notes]
    [notes.updates]
        title = "Component Updates"
        description = """\
Kubernetes: 1.30.1
Linux: 6.6.30
containerd: 2.0.0-rc.2
runc: 1.2.0-rc.1
etcd: 3.5.14

Talos is built with Go 1.22.3.
"""


    [notes.zstd]
        title = "ZSTD Compression"
        description = """\
Talos Linux now compresses kernel and initramfs using ZSTD.
Linux arm64 kernel is now compressed (previously it was uncompressed).
"""

    [notes.forward-kube-dns-to-host]
        title = "DNS Forwarding for CoreDNS pods"
        description = """\
Usage of the host DNS resolver as upstream for Kubernetes CoreDNS pods is now enabled by default. You can disable it
with:

```yaml
machine:
  features:
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: false
```

Please note that on running cluster you will have to kill CoreDNS pods for this change to apply.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
