# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.6.7"

pre_release = false

preface = """\
"""

[notes]
    [notes.updates]
        title = "Component Updates"
        description = """\
* Linux: 6.1.100
* Kubernetes: 1.29.7
* runc: 1.1.13
* containerd: 1.7.20

Talos is built with Go 1.21.12.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
