# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.6.0-beta.1"

pre_release = true

preface = """\
"""

[notes]
    [notes.updates]
        title = "Component Updates"
        description = """\
Linux: 6.1.73
etcd: 3.5.11
Kubernetes: 1.29.1
containerd: 1.7.12
runc: 1.1.11
Flannel: 0.24.1

Talos is built with Go 1.21.6.
"""

    [notes.device_selectors]
        title = "Device Selectors"
        description = """\
Talos Linux now supports `physical: true` qualifier for device selectors, it selects non-virtual network interfaces (i.e. `en0` is selected, while `bond0` is not).
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
