# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.7.0"

pre_release = true

preface = """\
"""

[notes]
    [notes.updates]
        title = "Component Updates"
        description = """\
Kubernetes: 1.31.0-alpha.3
Linux: 6.6.36
containerd: 2.0.0-rc.3
runc: 1.2.0-rc.2
etcd: 3.5.14
Flannel: 0.25.3
Flannel CNI plugin: 1.5.1

Talos is built with Go 1.22.5.
"""

    [notes.apparmor]
        title = "Workload Apparmor Profile"
        description = """\
Talos Linux can now apply the default AppArmor profiles to all workloads started via containerd, if the machine is installed with the AppArmor LSM enforced via the extraKernelArgs.

Eg:

```yaml
machine:
    install:
        extraKernelArgs:
            - security=apparmor
```
"""

    [notes.zstd]
        title = "ZSTD Compression"
        description = """\
Talos Linux now compresses kernel and initramfs using ZSTD.
Linux arm64 kernel is now compressed (previously it was uncompressed).
"""

    [notes.forward-kube-dns-to-host]
        title = "DNS Forwarding for CoreDNS pods"
        description = """\
Usage of the host DNS resolver as upstream for Kubernetes CoreDNS pods is now enabled by default. You can disable it
with:

```yaml
machine:
  features:
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: false
```

Please note that on running cluster you will have to kill CoreDNS pods for this change to apply.
"""

    [notes.lspci]
        title = "PCI Devices"
        description = """\
A list of PCI devices can now be obtained via `PCIDevices` resource, e.g. `talosctl get pcidevices`.
"""

    [notes.diagnostics]
        title = "Diagnostics"
        description = """\
Talos Linux now shows diagnostics information for common problems related to misconfiguration via `talosctl health` and Talos dashboard.
"""

    [notes.bridge]
        title = "Bridge Interface"
        description = """\
Talos Linux now support configuring 'vlan_filtering' for bridge interfaces.
"""

    [notes.proxy]
        title = "kube-proxy"
        description = """\
Talos Linux configures kube-proxy >= v1.31.0 to use 'nftables' backend by default.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
