# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.5.0"

pre_release = true

preface = """\
"""

[notes]
    [notes.firmware]
        title = "Linux Firmware"
        description = """\
Starting with Talos 1.6, there is no Linux firmware included in the initramfs.
Customers who need Linux firmware can pull them as extension during install time using the image factory service.
If the initial boot requires firmware, a custom iso can be built with the firmware included using the image factory service.
This also ensures that the linux-firmware is not tied to a specific Talos version.
"""

    [notes.updates]
        title = "Component Updates"
        description = """\
Linux: 6.1.58
containerd: 1.7.7
CoreDNS: 1.11.1
Kubernetes: 1.29.0-alpha.2
Flannel: 0.22.3
etcd: 3.5.10

Talos is built with Go 1.21.3.
"""

    [notes.talosctl]
        title = "talosctl CLI"
        description = """\
The command `images` deprecated in Talos 1.5 was removed, please use `talosctl images default` instead.
"""

    [notes.device-selectors]
        title = "Network Device Selectors"
        description = """\
Previously, [network device selectors](https://www.talos.dev/v1.6/talos-guides/network/device-selector/) only matched the first link, now the configuration is applied to all matching links.
"""


    [notes.kubeprism]
        title = "KubePrism"
        description = """\
[KubePrism](https://www.talos.dev/v1.6/kubernetes-guides/configuration/kubeprism/) is enabled by default on port 7445.
"""

    [notes.sysctl]
        title = "Sysctl"
        description = """\
Talos now handles sysctl/sysfs key names in line with sysctl.conf(5):

* if the first separator is '/', no conversion is done
* if the first separator is '.', dots and slashes are remapped

Example (both sysctls are equivalent):

```yaml
machine:
  sysctls:
    net/ipv6/conf/eth0.100/disable_ipv6: "1"
    net.ipv6.conf.eth0/100.disable_ipv6: "1"
```
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
