# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.4.3"

pre_release = false

preface = """\
"""

[notes]

    [notes.fixes]
        title = "Fixes"
        description="""\
This release fixes a bug that was introduced in Talos v1.4.2 and Talos v1.4.3 by updating Go to 1.20.4 which sets the default file rlimit to 1024.

See: #7198
"""

    [notes.updates]
        title = "Component Updates"
        description="""\
* Linux: 6.1.28
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
